// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoOutputFormat int32

const (
	VideoOutputFormat_MPEG_DASH VideoOutputFormat = 0
	VideoOutputFormat_HLS       VideoOutputFormat = 1
)

// Enum value maps for VideoOutputFormat.
var (
	VideoOutputFormat_name = map[int32]string{
		0: "MPEG_DASH",
		1: "HLS",
	}
	VideoOutputFormat_value = map[string]int32{
		"MPEG_DASH": 0,
		"HLS":       1,
	}
)

func (x VideoOutputFormat) Enum() *VideoOutputFormat {
	p := new(VideoOutputFormat)
	*p = x
	return p
}

func (x VideoOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (VideoOutputFormat) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x VideoOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoOutputFormat.Descriptor instead.
func (VideoOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type VideoResolution int32

const (
	VideoResolution_P144  VideoResolution = 0
	VideoResolution_P240  VideoResolution = 1
	VideoResolution_P360  VideoResolution = 2
	VideoResolution_P480  VideoResolution = 3
	VideoResolution_P720  VideoResolution = 4
	VideoResolution_P1080 VideoResolution = 5 // HD
	VideoResolution_P1440 VideoResolution = 6 // Ultra HD
	VideoResolution_P2160 VideoResolution = 7 // 4k
)

// Enum value maps for VideoResolution.
var (
	VideoResolution_name = map[int32]string{
		0: "P144",
		1: "P240",
		2: "P360",
		3: "P480",
		4: "P720",
		5: "P1080",
		6: "P1440",
		7: "P2160",
	}
	VideoResolution_value = map[string]int32{
		"P144":  0,
		"P240":  1,
		"P360":  2,
		"P480":  3,
		"P720":  4,
		"P1080": 5,
		"P1440": 6,
		"P2160": 7,
	}
)

func (x VideoResolution) Enum() *VideoResolution {
	p := new(VideoResolution)
	*p = x
	return p
}

func (x VideoResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (VideoResolution) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x VideoResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoResolution.Descriptor instead.
func (VideoResolution) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x2b, 0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x50, 0x45, 0x47, 0x5f, 0x44, 0x41, 0x53, 0x48, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x4c,
	0x53, 0x10, 0x01, 0x2a, 0x64, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x31, 0x34, 0x34, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x32, 0x34, 0x30, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x33,
	0x36, 0x30, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x34, 0x38, 0x30, 0x10, 0x03, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x37, 0x32, 0x30, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x31, 0x30, 0x38,
	0x30, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x31, 0x34, 0x34, 0x30, 0x10, 0x06, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x32, 0x31, 0x36, 0x30, 0x10, 0x07, 0x42, 0x09, 0x5a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_goTypes = []interface{}{
	(VideoOutputFormat)(0), // 0: common.VideoOutputFormat
	(VideoResolution)(0),   // 1: common.VideoResolution
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
