// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: Request.proto

package request

import (
	common "common/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcPath         string                   `protobuf:"bytes,1,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`    // s3 path to the video
	DestPath        string                   `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"` // unqiue s3 path to directory
	OutFormat       common.VideoOutputFormat `protobuf:"varint,3,opt,name=out_format,json=outFormat,proto3,enum=common.VideoOutputFormat" json:"out_format,omitempty"`
	ConvResolutions []common.VideoResolution `protobuf:"varint,4,rep,packed,name=conv_resolutions,json=convResolutions,proto3,enum=common.VideoResolution" json:"conv_resolutions,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *Request) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *Request) GetOutFormat() common.VideoOutputFormat {
	if x != nil {
		return x.OutFormat
	}
	return common.VideoOutputFormat(0)
}

func (x *Request) GetConvResolutions() []common.VideoResolution {
	if x != nil {
		return x.ConvResolutions
	}
	return nil
}

var File_Request_proto protoreflect.FileDescriptor

var file_Request_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72, 0x63, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x0a, 0x6f, 0x75,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x42, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Request_proto_rawDescOnce sync.Once
	file_Request_proto_rawDescData = file_Request_proto_rawDesc
)

func file_Request_proto_rawDescGZIP() []byte {
	file_Request_proto_rawDescOnce.Do(func() {
		file_Request_proto_rawDescData = protoimpl.X.CompressGZIP(file_Request_proto_rawDescData)
	})
	return file_Request_proto_rawDescData
}

var file_Request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Request_proto_goTypes = []interface{}{
	(*Request)(nil),               // 0: request.Request
	(common.VideoOutputFormat)(0), // 1: common.VideoOutputFormat
	(common.VideoResolution)(0),   // 2: common.VideoResolution
}
var file_Request_proto_depIdxs = []int32{
	1, // 0: request.Request.out_format:type_name -> common.VideoOutputFormat
	2, // 1: request.Request.conv_resolutions:type_name -> common.VideoResolution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Request_proto_init() }
func file_Request_proto_init() {
	if File_Request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Request_proto_goTypes,
		DependencyIndexes: file_Request_proto_depIdxs,
		MessageInfos:      file_Request_proto_msgTypes,
	}.Build()
	File_Request_proto = out.File
	file_Request_proto_rawDesc = nil
	file_Request_proto_goTypes = nil
	file_Request_proto_depIdxs = nil
}
